apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: kubernetes.io/basic-auth
stringData:
  username: mysql-pass
  #normally not a good idea to leave clear text in GitHub but the password will be hidden in k8
  #this is just for demo purposes.
  password: mypass1
